import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react';
import { useStore } from '../hooks/useStore';
import { CategoryType } from '../lib/types';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { balances, list, loading } = useStore(({ balances, list, loading }) => ({
    balances,
    list,
    loading: Boolean(loading.fetchFeed),
  }));

  useEffect(() => {
    useStore.getState().fetchFeed();
  }, []);

  if (loading) {
    return <h1>loading</h1>;
  }

  if (balances.length === 0) {
    return <h1>no content</h1>;
  }

  const { income, outcome } = balances[0];

  return (
    <div className={styles.container}>
      <Head>
        <title>Cai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          <p>本月支出: {outcome}</p>
          <p>本月收入: {income}</p>
          <p>本月差额: {income - outcome}</p>
        </p>

        <div className={styles.grid}>
          {list.map(record => (
            <p key={record.id} className={styles.card}>
              <p>{record.account?.name}</p>
              <p>{record.category?.subName || record.category?.name}</p>
              <p>{record.type === CategoryType.INCOME ? record.income : record.outcome}</p>
            </p>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
